/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './home';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/platform/platform';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from 'ionic-angular/components/toolbar/toolbar';
import * as import13 from 'ionic-angular/components/navbar/navbar';
import * as import14 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import15 from 'ionic-angular/components/content/content';
import * as import16 from 'ionic-angular/components/card/card';
import * as import17 from 'ionic-angular/components/grid/grid';
import * as import18 from 'ionic-angular/components/button/button';
import * as import19 from 'ionic-angular/config/config';
import * as import20 from '@angular/core/src/linker/element_ref';
import * as import21 from 'ionic-angular/navigation/view-controller';
import * as import22 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import23 from 'ionic-angular/components/app/app';
import * as import24 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import25 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import26 from 'ionic-angular/util/keyboard';
import * as import27 from '@angular/core/src/zone/ng_zone';
import * as import28 from 'ionic-angular/components/tabs/tabs';
import * as import29 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import30 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
var renderType_HomePage_Host:import0.RenderComponentType = (null as any);
class _View_HomePage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _HomePage_0_4:import3.HomePage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage_Host0,renderType_HomePage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-home',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HomePage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HomePage_0_4 = new import3.HomePage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.Platform));
    this._appEl_0.initComponent(this._HomePage_0_4,[],compView_0);
    compView_0.create(this._HomePage_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.HomePage) && (0 === requestNodeIndex))) { return this._HomePage_0_4; }
    return notFoundResult;
  }
}
function viewFactory_HomePage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_HomePage_Host === (null as any))) { (renderType_HomePage_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_HomePage_Host0(viewUtils,parentInjector,declarationEl);
}
export const HomePageNgFactory:import11.ComponentFactory<import3.HomePage> = new import11.ComponentFactory<import3.HomePage>('page-home',viewFactory_HomePage_Host0,import3.HomePage);
const styles_HomePage:any[] = [];
var renderType_HomePage:import0.RenderComponentType = (null as any);
class _View_HomePage0 extends import1.AppView<import3.HomePage> {
  _el_0:any;
  _Header_0_3:import12.Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _Navbar_2_4:import13.Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _ToolbarTitle_4_4:import14.ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _Content_9_4:import15.Content;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _Card_16_3:import16.Card;
  _text_17:any;
  _el_18:any;
  _CardHeader_18_3:import16.CardHeader;
  _text_19:any;
  _el_20:any;
  _Grid_20_3:import17.Grid;
  _text_21:any;
  _el_22:any;
  _Row_22_3:import17.Row;
  _text_23:any;
  _el_24:any;
  _Col_24_3:import17.Col;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _Col_27_3:import17.Col;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _Col_30_3:import17.Col;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _CardContent_36_3:import16.CardContent;
  _text_37:any;
  _el_38:any;
  _Grid_38_3:import17.Grid;
  _text_39:any;
  _el_40:any;
  _Row_40_3:import17.Row;
  _text_41:any;
  _el_42:any;
  _Col_42_3:import17.Col;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  _Col_54_3:import17.Col;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _el_60:any;
  _text_61:any;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _text_65:any;
  _el_66:any;
  _Col_66_3:import17.Col;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _el_70:any;
  _text_71:any;
  _el_72:any;
  _text_73:any;
  _text_74:any;
  _el_75:any;
  _text_76:any;
  _text_77:any;
  _text_78:any;
  _text_79:any;
  _text_80:any;
  _text_81:any;
  _el_82:any;
  _text_83:any;
  _text_84:any;
  _el_85:any;
  _Card_85_3:import16.Card;
  _text_86:any;
  _el_87:any;
  _CardHeader_87_3:import16.CardHeader;
  _text_88:any;
  _el_89:any;
  _Grid_89_3:import17.Grid;
  _text_90:any;
  _el_91:any;
  _Row_91_3:import17.Row;
  _text_92:any;
  _el_93:any;
  _Col_93_3:import17.Col;
  _text_94:any;
  _text_95:any;
  _el_96:any;
  _Col_96_3:import17.Col;
  _text_97:any;
  _text_98:any;
  _el_99:any;
  _Col_99_3:import17.Col;
  _text_100:any;
  _text_101:any;
  _text_102:any;
  _text_103:any;
  _text_104:any;
  _el_105:any;
  _CardContent_105_3:import16.CardContent;
  _text_106:any;
  _el_107:any;
  _Grid_107_3:import17.Grid;
  _text_108:any;
  _el_109:any;
  _Row_109_3:import17.Row;
  _text_110:any;
  _el_111:any;
  _Col_111_3:import17.Col;
  _text_112:any;
  _el_113:any;
  _text_114:any;
  _text_115:any;
  _el_116:any;
  _Col_116_3:import17.Col;
  _text_117:any;
  _el_118:any;
  _text_119:any;
  _text_120:any;
  _el_121:any;
  _Col_121_3:import17.Col;
  _text_122:any;
  _el_123:any;
  _text_124:any;
  _text_125:any;
  _text_126:any;
  _text_127:any;
  _text_128:any;
  _text_129:any;
  _text_130:any;
  _el_131:any;
  _text_132:any;
  _el_133:any;
  _text_134:any;
  _text_135:any;
  _el_136:any;
  _text_137:any;
  _el_138:any;
  _text_139:any;
  _text_140:any;
  _text_141:any;
  _el_142:any;
  _Footer_142_3:import12.Footer;
  _text_143:any;
  _el_144:any;
  /*private*/ _appEl_144:import2.AppElement;
  _Toolbar_144_4:import12.Toolbar;
  _text_145:any;
  _el_146:any;
  _Grid_146_3:import17.Grid;
  _text_147:any;
  _el_148:any;
  _Row_148_3:import17.Row;
  _text_149:any;
  _el_150:any;
  _Col_150_3:import17.Col;
  _text_151:any;
  _el_152:any;
  /*private*/ _appEl_152:import2.AppElement;
  _Button_152_4:import18.Button;
  _text_153:any;
  _text_154:any;
  _text_155:any;
  _el_156:any;
  _Col_156_3:import17.Col;
  _text_157:any;
  _el_158:any;
  /*private*/ _appEl_158:import2.AppElement;
  _Button_158_4:import18.Button;
  _text_159:any;
  _text_160:any;
  _text_161:any;
  _text_162:any;
  _text_163:any;
  _text_164:any;
  _text_165:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HomePage0,renderType_HomePage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import12.Header(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import21.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this.renderer.setElementAttribute(this._el_2,'color','primary');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import22.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import13.Navbar(this.parentInjector.get(import23.App),this.parentInjector.get(import21.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import24.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import14.ToolbarTitle(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import12.Toolbar,(null as any)),this._Navbar_2_4);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4,[],compView_4);
    this._text_5 = this.renderer.createText((null as any),'\n            Mérés\n        ',(null as any));
    compView_4.create(this._ToolbarTitle_4_4,[[].concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_2.create(this._Navbar_2_4,[
      [],
      [],
      [],
      [].concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_9,'padding','');
    this._appEl_9 = new import2.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import25.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import15.Content(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import23.App),this.parentInjector.get(import26.Keyboard),this.parentInjector.get(import27.NgZone),this.parentInjector.get(import21.ViewController,(null as any)),this.parentInjector.get(import28.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4,[],compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','container');
    this._text_12 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'p',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','accTitle');
    this._text_14 = this.renderer.createText(this._el_13,'Gyorsulás: ',(null as any));
    this._text_15 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_11,'ion-card',(null as any));
    this._Card_16_3 = new import16.Card(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_16),this.renderer);
    this._text_17 = this.renderer.createText(this._el_16,'\n            ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'ion-card-header',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','header-padding');
    this._CardHeader_18_3 = new import16.CardHeader();
    this._text_19 = this.renderer.createText(this._el_18,'\n                ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'ion-grid',(null as any));
    this._Grid_20_3 = new import17.Grid();
    this._text_21 = this.renderer.createText(this._el_20,'\n                    ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_20,'ion-row',(null as any));
    this._Row_22_3 = new import17.Row();
    this._text_23 = this.renderer.createText(this._el_22,'\n                        ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_22,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','cord');
    this.renderer.setElementAttribute(this._el_24,'text-center','');
    this.renderer.setElementAttribute(this._el_24,'width-33','');
    this._Col_24_3 = new import17.Col();
    this._text_25 = this.renderer.createText(this._el_24,'\n                            X\n                        ',(null as any));
    this._text_26 = this.renderer.createText(this._el_22,'\n                        ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_22,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_27,'class','cord');
    this.renderer.setElementAttribute(this._el_27,'text-center','');
    this.renderer.setElementAttribute(this._el_27,'width-33','');
    this._Col_27_3 = new import17.Col();
    this._text_28 = this.renderer.createText(this._el_27,'\n                            Y\n                        ',(null as any));
    this._text_29 = this.renderer.createText(this._el_22,'\n                        ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_22,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','cord');
    this.renderer.setElementAttribute(this._el_30,'text-center','');
    this.renderer.setElementAttribute(this._el_30,'width-33','');
    this._Col_30_3 = new import17.Col();
    this._text_31 = this.renderer.createText(this._el_30,'\n                            Z\n                        ',(null as any));
    this._text_32 = this.renderer.createText(this._el_22,'\n                    ',(null as any));
    this._text_33 = this.renderer.createText(this._el_20,'\n                ',(null as any));
    this._text_34 = this.renderer.createText(this._el_18,'\n            ',(null as any));
    this._text_35 = this.renderer.createText(this._el_16,'\n            ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_16,'ion-card-content',(null as any));
    this.renderer.setElementAttribute(this._el_36,'class','content-padding');
    this._CardContent_36_3 = new import16.CardContent();
    this._text_37 = this.renderer.createText(this._el_36,'\n                ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_36,'ion-grid',(null as any));
    this._Grid_38_3 = new import17.Grid();
    this._text_39 = this.renderer.createText(this._el_38,'\n                    ',(null as any));
    this._el_40 = this.renderer.createElement(this._el_38,'ion-row',(null as any));
    this._Row_40_3 = new import17.Row();
    this._text_41 = this.renderer.createText(this._el_40,'\n                        ',(null as any));
    this._el_42 = this.renderer.createElement(this._el_40,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_42,'text-center','');
    this.renderer.setElementAttribute(this._el_42,'width-33','');
    this._Col_42_3 = new import17.Col();
    this._text_43 = this.renderer.createText(this._el_42,'\n                            ',(null as any));
    this._el_44 = this.renderer.createElement(this._el_42,'div',(null as any));
    this.renderer.setElementAttribute(this._el_44,'class','acceleration');
    this._text_45 = this.renderer.createText(this._el_42,'\n                            ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_42,'div',(null as any));
    this.renderer.setElementAttribute(this._el_46,'class','unit');
    this._text_47 = this.renderer.createText(this._el_46,'m/s',(null as any));
    this._el_48 = this.renderer.createElement(this._el_46,'span',(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'2',(null as any));
    this._text_50 = this.renderer.createText(this._el_42,'\n                            ',(null as any));
    this._el_51 = this.renderer.createElement(this._el_42,'div',(null as any));
    this.renderer.setElementAttribute(this._el_51,'class','clear');
    this._text_52 = this.renderer.createText(this._el_42,'\n                        ',(null as any));
    this._text_53 = this.renderer.createText(this._el_40,'\n                        ',(null as any));
    this._el_54 = this.renderer.createElement(this._el_40,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_54,'text-center','');
    this.renderer.setElementAttribute(this._el_54,'width-33','');
    this._Col_54_3 = new import17.Col();
    this._text_55 = this.renderer.createText(this._el_54,'\n                            ',(null as any));
    this._el_56 = this.renderer.createElement(this._el_54,'div',(null as any));
    this.renderer.setElementAttribute(this._el_56,'class','acceleration');
    this._text_57 = this.renderer.createText(this._el_54,'\n                            ',(null as any));
    this._el_58 = this.renderer.createElement(this._el_54,'div',(null as any));
    this.renderer.setElementAttribute(this._el_58,'class','unit');
    this._text_59 = this.renderer.createText(this._el_58,'m/s',(null as any));
    this._el_60 = this.renderer.createElement(this._el_58,'span',(null as any));
    this._text_61 = this.renderer.createText(this._el_60,'2',(null as any));
    this._text_62 = this.renderer.createText(this._el_54,'\n                            ',(null as any));
    this._el_63 = this.renderer.createElement(this._el_54,'div',(null as any));
    this.renderer.setElementAttribute(this._el_63,'class','clear');
    this._text_64 = this.renderer.createText(this._el_54,'\n                        ',(null as any));
    this._text_65 = this.renderer.createText(this._el_40,'\n                        ',(null as any));
    this._el_66 = this.renderer.createElement(this._el_40,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_66,'text-center','');
    this.renderer.setElementAttribute(this._el_66,'width-33','');
    this._Col_66_3 = new import17.Col();
    this._text_67 = this.renderer.createText(this._el_66,'\n                            ',(null as any));
    this._el_68 = this.renderer.createElement(this._el_66,'div',(null as any));
    this.renderer.setElementAttribute(this._el_68,'class','acceleration');
    this._text_69 = this.renderer.createText(this._el_66,'\n                            ',(null as any));
    this._el_70 = this.renderer.createElement(this._el_66,'div',(null as any));
    this.renderer.setElementAttribute(this._el_70,'class','unit');
    this._text_71 = this.renderer.createText(this._el_70,'m/s',(null as any));
    this._el_72 = this.renderer.createElement(this._el_70,'span',(null as any));
    this._text_73 = this.renderer.createText(this._el_72,'2',(null as any));
    this._text_74 = this.renderer.createText(this._el_66,'\n                            ',(null as any));
    this._el_75 = this.renderer.createElement(this._el_66,'div',(null as any));
    this.renderer.setElementAttribute(this._el_75,'class','clear');
    this._text_76 = this.renderer.createText(this._el_66,'\n                        ',(null as any));
    this._text_77 = this.renderer.createText(this._el_40,'\n                    ',(null as any));
    this._text_78 = this.renderer.createText(this._el_38,'\n                ',(null as any));
    this._text_79 = this.renderer.createText(this._el_36,'\n            ',(null as any));
    this._text_80 = this.renderer.createText(this._el_16,'\n        ',(null as any));
    this._text_81 = this.renderer.createText(this._el_11,'\n\n\n        ',(null as any));
    this._el_82 = this.renderer.createElement(this._el_11,'p',(null as any));
    this.renderer.setElementAttribute(this._el_82,'class','locTitle');
    this._text_83 = this.renderer.createText(this._el_82,'Gps: ',(null as any));
    this._text_84 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_85 = this.renderer.createElement(this._el_11,'ion-card',(null as any));
    this._Card_85_3 = new import16.Card(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_85),this.renderer);
    this._text_86 = this.renderer.createText(this._el_85,'\n            ',(null as any));
    this._el_87 = this.renderer.createElement(this._el_85,'ion-card-header',(null as any));
    this.renderer.setElementAttribute(this._el_87,'class','header-padding');
    this._CardHeader_87_3 = new import16.CardHeader();
    this._text_88 = this.renderer.createText(this._el_87,'\n                ',(null as any));
    this._el_89 = this.renderer.createElement(this._el_87,'ion-grid',(null as any));
    this._Grid_89_3 = new import17.Grid();
    this._text_90 = this.renderer.createText(this._el_89,'\n                    ',(null as any));
    this._el_91 = this.renderer.createElement(this._el_89,'ion-row',(null as any));
    this._Row_91_3 = new import17.Row();
    this._text_92 = this.renderer.createText(this._el_91,'\n                        ',(null as any));
    this._el_93 = this.renderer.createElement(this._el_91,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_93,'class','cord');
    this.renderer.setElementAttribute(this._el_93,'text-center','');
    this.renderer.setElementAttribute(this._el_93,'width-33','');
    this._Col_93_3 = new import17.Col();
    this._text_94 = this.renderer.createText(this._el_93,'\n                            SZ\n                        ',(null as any));
    this._text_95 = this.renderer.createText(this._el_91,'\n                        ',(null as any));
    this._el_96 = this.renderer.createElement(this._el_91,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_96,'class','cord');
    this.renderer.setElementAttribute(this._el_96,'text-center','');
    this.renderer.setElementAttribute(this._el_96,'width-33','');
    this._Col_96_3 = new import17.Col();
    this._text_97 = this.renderer.createText(this._el_96,'\n                            H\n                        ',(null as any));
    this._text_98 = this.renderer.createText(this._el_91,'\n                        ',(null as any));
    this._el_99 = this.renderer.createElement(this._el_91,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_99,'class','cord');
    this.renderer.setElementAttribute(this._el_99,'text-center','');
    this.renderer.setElementAttribute(this._el_99,'width-33','');
    this._Col_99_3 = new import17.Col();
    this._text_100 = this.renderer.createText(this._el_99,'\n                            M\n                        ',(null as any));
    this._text_101 = this.renderer.createText(this._el_91,'\n                    ',(null as any));
    this._text_102 = this.renderer.createText(this._el_89,'\n                ',(null as any));
    this._text_103 = this.renderer.createText(this._el_87,'\n            ',(null as any));
    this._text_104 = this.renderer.createText(this._el_85,'\n            ',(null as any));
    this._el_105 = this.renderer.createElement(this._el_85,'ion-card-content',(null as any));
    this.renderer.setElementAttribute(this._el_105,'class','content-padding');
    this._CardContent_105_3 = new import16.CardContent();
    this._text_106 = this.renderer.createText(this._el_105,'\n                ',(null as any));
    this._el_107 = this.renderer.createElement(this._el_105,'ion-grid',(null as any));
    this._Grid_107_3 = new import17.Grid();
    this._text_108 = this.renderer.createText(this._el_107,'\n                    ',(null as any));
    this._el_109 = this.renderer.createElement(this._el_107,'ion-row',(null as any));
    this._Row_109_3 = new import17.Row();
    this._text_110 = this.renderer.createText(this._el_109,'\n                        ',(null as any));
    this._el_111 = this.renderer.createElement(this._el_109,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_111,'text-center','');
    this.renderer.setElementAttribute(this._el_111,'width-33','');
    this._Col_111_3 = new import17.Col();
    this._text_112 = this.renderer.createText(this._el_111,'\n                            ',(null as any));
    this._el_113 = this.renderer.createElement(this._el_111,'div',(null as any));
    this.renderer.setElementAttribute(this._el_113,'class','geolocation');
    this._text_114 = this.renderer.createText(this._el_111,'\n                        ',(null as any));
    this._text_115 = this.renderer.createText(this._el_109,'\n                        ',(null as any));
    this._el_116 = this.renderer.createElement(this._el_109,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_116,'text-center','');
    this.renderer.setElementAttribute(this._el_116,'width-33','');
    this._Col_116_3 = new import17.Col();
    this._text_117 = this.renderer.createText(this._el_116,'\n                            ',(null as any));
    this._el_118 = this.renderer.createElement(this._el_116,'div',(null as any));
    this.renderer.setElementAttribute(this._el_118,'class','geolocation');
    this._text_119 = this.renderer.createText(this._el_116,'\n                        ',(null as any));
    this._text_120 = this.renderer.createText(this._el_109,'\n                        ',(null as any));
    this._el_121 = this.renderer.createElement(this._el_109,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_121,'text-center','');
    this.renderer.setElementAttribute(this._el_121,'width-33','');
    this._Col_121_3 = new import17.Col();
    this._text_122 = this.renderer.createText(this._el_121,'\n                            ',(null as any));
    this._el_123 = this.renderer.createElement(this._el_121,'div',(null as any));
    this.renderer.setElementAttribute(this._el_123,'class','geolocation');
    this._text_124 = this.renderer.createText(this._el_121,'\n                        ',(null as any));
    this._text_125 = this.renderer.createText(this._el_109,'\n                    ',(null as any));
    this._text_126 = this.renderer.createText(this._el_107,'\n                ',(null as any));
    this._text_127 = this.renderer.createText(this._el_105,'\n            ',(null as any));
    this._text_128 = this.renderer.createText(this._el_85,'\n        ',(null as any));
    this._text_129 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._text_130 = this.renderer.createText((null as any),'\n\n\n    ',(null as any));
    this._el_131 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_131,'class','time');
    this._text_132 = this.renderer.createText(this._el_131,'\n        ',(null as any));
    this._el_133 = this.renderer.createElement(this._el_131,'span',(null as any));
    this.renderer.setElementAttribute(this._el_133,'class','record');
    this._text_134 = this.renderer.createText(this._el_133,'Felvétel: ',(null as any));
    this._text_135 = this.renderer.createText(this._el_131,'\n        ',(null as any));
    this._el_136 = this.renderer.createElement(this._el_131,'span',(null as any));
    this.renderer.setElementAttribute(this._el_136,'class','minutes');
    this._text_137 = this.renderer.createText(this._el_131,'\n        ',(null as any));
    this._el_138 = this.renderer.createElement(this._el_131,'span',(null as any));
    this.renderer.setElementAttribute(this._el_138,'class','seconds');
    this._text_139 = this.renderer.createText(this._el_131,'\n    ',(null as any));
    this._text_140 = this.renderer.createText((null as any),'\n',(null as any));
    compView_9.create(this._Content_9_4,[
      [],
      [].concat([
        this._text_10,
        this._el_11,
        this._text_130,
        this._el_131,
        this._text_140
      ]
      ),
      []
    ]
    ,(null as any));
    this._text_141 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_142 = this.renderer.createElement(parentRenderNode,'ion-footer',(null as any));
    this._Footer_142_3 = new import12.Footer(this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_142),this.renderer,this.parentInjector.get(import21.ViewController,(null as any)));
    this._text_143 = this.renderer.createText(this._el_142,'\n        ',(null as any));
    this._el_144 = this.renderer.createElement(this._el_142,'ion-toolbar',(null as any));
    this.renderer.setElementAttribute(this._el_144,'class','toolbar');
    this.renderer.setElementAttribute(this._el_144,'color','primary');
    this._appEl_144 = new import2.AppElement(144,142,this,this._el_144);
    var compView_144:any = import29.viewFactory_Toolbar0(this.viewUtils,this.injector(144),this._appEl_144);
    this._Toolbar_144_4 = new import12.Toolbar(this.parentInjector.get(import21.ViewController,(null as any)),this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_144),this.renderer);
    this._appEl_144.initComponent(this._Toolbar_144_4,[],compView_144);
    this._text_145 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_146 = this.renderer.createElement((null as any),'ion-grid',(null as any));
    this._Grid_146_3 = new import17.Grid();
    this._text_147 = this.renderer.createText(this._el_146,'\n                ',(null as any));
    this._el_148 = this.renderer.createElement(this._el_146,'ion-row',(null as any));
    this._Row_148_3 = new import17.Row();
    this._text_149 = this.renderer.createText(this._el_148,'\n                    ',(null as any));
    this._el_150 = this.renderer.createElement(this._el_148,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_150,'text-center','');
    this.renderer.setElementAttribute(this._el_150,'width-50','');
    this._Col_150_3 = new import17.Col();
    this._text_151 = this.renderer.createText(this._el_150,'\n                        ',(null as any));
    this._el_152 = this.renderer.createElement(this._el_150,'button',(null as any));
    this.renderer.setElementAttribute(this._el_152,'color','light');
    this.renderer.setElementAttribute(this._el_152,'ion-button','');
    this.renderer.setElementAttribute(this._el_152,'outline','');
    this._appEl_152 = new import2.AppElement(152,150,this,this._el_152);
    var compView_152:any = import30.viewFactory_Button0(this.viewUtils,this.injector(152),this._appEl_152);
    this._Button_152_4 = new import18.Button((null as any),'',this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_152),this.renderer);
    this._appEl_152.initComponent(this._Button_152_4,[],compView_152);
    this._text_153 = this.renderer.createText((null as any),'\n                            Inditás\n                        ',(null as any));
    compView_152.create(this._Button_152_4,[[].concat([this._text_153])],(null as any));
    this._text_154 = this.renderer.createText(this._el_150,'\n                    ',(null as any));
    this._text_155 = this.renderer.createText(this._el_148,'\n                    ',(null as any));
    this._el_156 = this.renderer.createElement(this._el_148,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_156,'text-center','');
    this.renderer.setElementAttribute(this._el_156,'width-50','');
    this._Col_156_3 = new import17.Col();
    this._text_157 = this.renderer.createText(this._el_156,'\n                        ',(null as any));
    this._el_158 = this.renderer.createElement(this._el_156,'button',(null as any));
    this.renderer.setElementAttribute(this._el_158,'color','light');
    this.renderer.setElementAttribute(this._el_158,'ion-button','');
    this.renderer.setElementAttribute(this._el_158,'outline','');
    this._appEl_158 = new import2.AppElement(158,156,this,this._el_158);
    var compView_158:any = import30.viewFactory_Button0(this.viewUtils,this.injector(158),this._appEl_158);
    this._Button_158_4 = new import18.Button((null as any),'',this.parentInjector.get(import19.Config),new import20.ElementRef(this._el_158),this.renderer);
    this._appEl_158.initComponent(this._Button_158_4,[],compView_158);
    this._text_159 = this.renderer.createText((null as any),'\n                            Leállitás\n                        ',(null as any));
    compView_158.create(this._Button_158_4,[[].concat([this._text_159])],(null as any));
    this._text_160 = this.renderer.createText(this._el_156,'\n                    ',(null as any));
    this._text_161 = this.renderer.createText(this._el_148,'\n                ',(null as any));
    this._text_162 = this.renderer.createText(this._el_146,'\n            ',(null as any));
    this._text_163 = this.renderer.createText((null as any),'\n        ',(null as any));
    compView_144.create(this._Toolbar_144_4,[
      [],
      [],
      [],
      [].concat([
        this._text_145,
        this._el_146,
        this._text_163
      ]
      )
    ]
    ,(null as any));
    this._text_164 = this.renderer.createText(this._el_142,'\n    ',(null as any));
    this._text_165 = this.renderer.createText(parentRenderNode,'\n\n\n\n\n\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_152,'click',this.eventHandler(this._handle_click_152_0.bind(this)));
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_158,'click',this.eventHandler(this._handle_click_158_0.bind(this)));
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._text_74,
      this._el_75,
      this._text_76,
      this._text_77,
      this._text_78,
      this._text_79,
      this._text_80,
      this._text_81,
      this._el_82,
      this._text_83,
      this._text_84,
      this._el_85,
      this._text_86,
      this._el_87,
      this._text_88,
      this._el_89,
      this._text_90,
      this._el_91,
      this._text_92,
      this._el_93,
      this._text_94,
      this._text_95,
      this._el_96,
      this._text_97,
      this._text_98,
      this._el_99,
      this._text_100,
      this._text_101,
      this._text_102,
      this._text_103,
      this._text_104,
      this._el_105,
      this._text_106,
      this._el_107,
      this._text_108,
      this._el_109,
      this._text_110,
      this._el_111,
      this._text_112,
      this._el_113,
      this._text_114,
      this._text_115,
      this._el_116,
      this._text_117,
      this._el_118,
      this._text_119,
      this._text_120,
      this._el_121,
      this._text_122,
      this._el_123,
      this._text_124,
      this._text_125,
      this._text_126,
      this._text_127,
      this._text_128,
      this._text_129,
      this._text_130,
      this._el_131,
      this._text_132,
      this._el_133,
      this._text_134,
      this._text_135,
      this._el_136,
      this._text_137,
      this._el_138,
      this._text_139,
      this._text_140,
      this._text_141,
      this._el_142,
      this._text_143,
      this._el_144,
      this._text_145,
      this._el_146,
      this._text_147,
      this._el_148,
      this._text_149,
      this._el_150,
      this._text_151,
      this._el_152,
      this._text_153,
      this._text_154,
      this._text_155,
      this._el_156,
      this._text_157,
      this._el_158,
      this._text_159,
      this._text_160,
      this._text_161,
      this._text_162,
      this._text_163,
      this._text_164,
      this._text_165
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4; }
    if (((token === import13.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4; }
    if (((token === import12.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3; }
    if (((token === import17.Col) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._Col_24_3; }
    if (((token === import17.Col) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Col_27_3; }
    if (((token === import17.Col) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Col_30_3; }
    if (((token === import17.Row) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._Row_22_3; }
    if (((token === import17.Grid) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._Grid_20_3; }
    if (((token === import16.CardHeader) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._CardHeader_18_3; }
    if (((token === import17.Col) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._Col_42_3; }
    if (((token === import17.Col) && ((54 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._Col_54_3; }
    if (((token === import17.Col) && ((66 <= requestNodeIndex) && (requestNodeIndex <= 76)))) { return this._Col_66_3; }
    if (((token === import17.Row) && ((40 <= requestNodeIndex) && (requestNodeIndex <= 77)))) { return this._Row_40_3; }
    if (((token === import17.Grid) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 78)))) { return this._Grid_38_3; }
    if (((token === import16.CardContent) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 79)))) { return this._CardContent_36_3; }
    if (((token === import16.Card) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 80)))) { return this._Card_16_3; }
    if (((token === import17.Col) && ((93 <= requestNodeIndex) && (requestNodeIndex <= 94)))) { return this._Col_93_3; }
    if (((token === import17.Col) && ((96 <= requestNodeIndex) && (requestNodeIndex <= 97)))) { return this._Col_96_3; }
    if (((token === import17.Col) && ((99 <= requestNodeIndex) && (requestNodeIndex <= 100)))) { return this._Col_99_3; }
    if (((token === import17.Row) && ((91 <= requestNodeIndex) && (requestNodeIndex <= 101)))) { return this._Row_91_3; }
    if (((token === import17.Grid) && ((89 <= requestNodeIndex) && (requestNodeIndex <= 102)))) { return this._Grid_89_3; }
    if (((token === import16.CardHeader) && ((87 <= requestNodeIndex) && (requestNodeIndex <= 103)))) { return this._CardHeader_87_3; }
    if (((token === import17.Col) && ((111 <= requestNodeIndex) && (requestNodeIndex <= 114)))) { return this._Col_111_3; }
    if (((token === import17.Col) && ((116 <= requestNodeIndex) && (requestNodeIndex <= 119)))) { return this._Col_116_3; }
    if (((token === import17.Col) && ((121 <= requestNodeIndex) && (requestNodeIndex <= 124)))) { return this._Col_121_3; }
    if (((token === import17.Row) && ((109 <= requestNodeIndex) && (requestNodeIndex <= 125)))) { return this._Row_109_3; }
    if (((token === import17.Grid) && ((107 <= requestNodeIndex) && (requestNodeIndex <= 126)))) { return this._Grid_107_3; }
    if (((token === import16.CardContent) && ((105 <= requestNodeIndex) && (requestNodeIndex <= 127)))) { return this._CardContent_105_3; }
    if (((token === import16.Card) && ((85 <= requestNodeIndex) && (requestNodeIndex <= 128)))) { return this._Card_85_3; }
    if (((token === import15.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 140)))) { return this._Content_9_4; }
    if (((token === import18.Button) && ((152 <= requestNodeIndex) && (requestNodeIndex <= 153)))) { return this._Button_152_4; }
    if (((token === import17.Col) && ((150 <= requestNodeIndex) && (requestNodeIndex <= 154)))) { return this._Col_150_3; }
    if (((token === import18.Button) && ((158 <= requestNodeIndex) && (requestNodeIndex <= 159)))) { return this._Button_158_4; }
    if (((token === import17.Col) && ((156 <= requestNodeIndex) && (requestNodeIndex <= 160)))) { return this._Col_156_3; }
    if (((token === import17.Row) && ((148 <= requestNodeIndex) && (requestNodeIndex <= 161)))) { return this._Row_148_3; }
    if (((token === import17.Grid) && ((146 <= requestNodeIndex) && (requestNodeIndex <= 162)))) { return this._Grid_146_3; }
    if (((token === import12.Toolbar) && ((144 <= requestNodeIndex) && (requestNodeIndex <= 163)))) { return this._Toolbar_144_4; }
    if (((token === import12.Footer) && ((142 <= requestNodeIndex) && (requestNodeIndex <= 164)))) { return this._Footer_142_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    const currVal_0:any = 'primary';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._Navbar_2_4.color = currVal_0;
      this._expr_0 = currVal_0;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Content_9_4.ngOnInit(); }
    changed = false;
    const currVal_12:any = 'primary';
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._Toolbar_144_4.color = currVal_12;
      changed = true;
      this._expr_12 = currVal_12;
    }
    if (changed) { this._appEl_144.componentView.markAsCheckOnce(); }
    changed = false;
    const currVal_15:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._Button_152_4.outline = currVal_15;
      changed = true;
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = 'light';
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._Button_152_4.color = currVal_16;
      changed = true;
      this._expr_16 = currVal_16;
    }
    if (changed) { this._appEl_152.componentView.markAsCheckOnce(); }
    changed = false;
    const currVal_18:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this._Button_158_4.outline = currVal_18;
      changed = true;
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = 'light';
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this._Button_158_4.color = currVal_19;
      changed = true;
      this._expr_19 = currVal_19;
    }
    if (changed) { this._appEl_158.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Button_152_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_158_4.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_2_4._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_2_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Content_9_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this.context.accelerometerX;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_44,'innerText',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this.context.accelerometerX;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_56,'innerText',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this.context.accelerometerZ;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementProperty(this._el_68,'innerText',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this.context.latitude;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementProperty(this._el_113,'innerText',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this.context.longitude;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementProperty(this._el_118,'innerText',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this.context.altitude;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementProperty(this._el_123,'innerText',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this.context.showMinutes;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementProperty(this._el_136,'innerText',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this.context.showSeconds;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementProperty(this._el_138,'innerText',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_13:any = this._Toolbar_144_4._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_144,'statusbar-padding',currVal_13);
      this._expr_13 = currVal_13;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_9_4.ngOnDestroy();
  }
  private _handle_click_152_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.startB()) !== false);
    return (true && pd_0);
  }
  private _handle_click_158_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.stopB()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_HomePage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.HomePage> {
  if ((renderType_HomePage === (null as any))) { (renderType_HomePage = viewUtils.createRenderComponentType('D:/Ionic2/sensorApp/.tmp/pages/home/home.html',0,import10.ViewEncapsulation.None,styles_HomePage,{})); }
  return new _View_HomePage0(viewUtils,parentInjector,declarationEl);
}